cockpit-project/cockpit-project.github.io

running.html

The SSL access that fedorapeople.org enforces causes problems.
Our packages are already signed.

Push debian repo to rhcloud.com

---

running.html

systemctl: unrecognized option '--now'

Debian Jessie has no systemctl enable --now option

---

running.html

Fedora use dnf as default package manager. So I changed yum command with dnf.

Replace yum to dnf for Fedora

---

running.html

Show more secure key ID and fingerprint (verified on master key on the release machine), and drop obsolete `systemctl enable/start` commands.

Update Debian/Ubuntu install instructions

---

running.html

Cockpit is now in the official stretch-backports, for current Debian
stable (9.x).
Give copy&pasteable instructions for adding the repository instead of
asking the user to interactively edit the apt sources. Do the same for
Debian 8.

Running: Add install instructions for Debian 9

---

running.md

Port commit 6379b08 over to the new Jekyll website, as the conversion
branched off before that commit.
Add explicit line breaks and \ to the commands to avoid line breaks.
Rename the capture labels to something more suitable.

Running: Re-add install instructions for Debian 9

---

assets/site.sass

This makes the content of the guide header fit into the maximum width of the page.

apply gutter width to guide pages as well

---

running.md

Cockpit is now in official jessie-backports-sloppy, for old stable 8.x.
This is built for all architectures, so in particular this can now be
used on Raspian (see https://github.com/cockpit-project/cockpit/issues/6560).

Running: Update install instructions for Debian 8

---

README.md

Either the command changed in Jekyll to not default to `server`, or I was remembering Middleman instructions when I wrote this. :wink:

fixed Jekyll commmand

---

_data/navigation.yml
_scripts/update-external-docs.rb
external/source/HACKING.md
external/source/test/README.md
external/wiki/Cockpit-Coding-Guidelines.md
external/wiki/Contributing.md
external/wiki/Workflow.md

Currently, there are a bunch of useful docs that are not included on the project website (and, as such, are not indexed so that they can be searched).
I've written a script (which can be run periodically, and would be ideal to be run by a bot) and made a few commits to fix this visibility issue:
- added a script to fetch the latest versions of selected documents from the Cockpit git source and project wiki
- committed current version of docs
- pointed the contribute nav link to the included document
A nice side-effect of these changes is that we can have all the navigation at the top of the page stay within the website as well.

External documentation

---

_layouts/guide.html
assets/site.sass

- rewrote HTML a bit further (to include viewport, manifest, favicon, etc.)
- added guide-specific CSS to:
- set max-width for `<pre>`
- make `<pre>` scrolly when it overflows
- made header `sticky` to improve navigation

improved guide's mobile experience & site integration

---

assets/site.sass

This fixes Epiphany and should also fix Safari (which is basically its sibling in the browser world, as they share the same rendering engine).

added CSS fallback to static for browsers that don't support sticky

---

running.md

`atomic install` is explicitly necessary, otherwise it does not get
properly installed.
Fixes #116

running: Fix Atomic install instructions

---

_config.yml
_includes/post.html
assets/lib/blog.sass

Improved blog summaries in `/blog/`.
This is much tidier for everyone and reduces the amount of unnecessary information for screen readers.

Blog summary improvements

---

_config.yml
assets/site.sass

Making the articles wrap nicely, thanks to CSS grids (in browsers that support it, which is everything but IE). It also changes pagination from 10 to 12 — which is nice, as it's a multiple of both 2 and 3 (meaning grids 3 items wide and 2 items wide both wrap perfectly).
For non-grid-supporting browsers, this changes nothing but pagination to include 2 more items.
(Browsers support unprefixed grid are at 90% — the only notible browsers that do not are IE, old versions of Edge (before Oct 2017), Opera Mini and Android versions below 4. In the case of mobile browsers, this changes nothing but pagination count anyway. This change is mainly for desktop and tablet users.)
See: https://caniuse.com/#feat=css-grid for browser support details.

blog: display articles in a grid

---

running.md

- IE10 is completely dead, even according to Microsoft. 
- We use several features that are really dodgy, if supported at all in IE10.
- IE11 is the last version, so there's no `+` anymore.

running: bumped up browser requirements to IE11

---

blog/feeds/index.md
blog/index.html
index.md

- added link to front page's mini-footer
- added link on /blog/
- added link to /blog/ on /blog/feeds/

blog: make atom feeds more discoverable

---

blog/feeds/index.md
blog/index.html

I added a few minor fixups to make these blog-related links work on baseurls that aren't domains (that is: on people's forks that serve as staging sites).
_Usually_ this is automatically handled by some magic I wrote in the layout code — but, as you can see, not always.

blog: fixed blog links with baseurls

---

_config.yml

Documentation: https://jekyllrb.com/docs/configuration/#build-command-options
Default is "false". We want "true", just in case the time is a little in the future. (Timezones could possibly get in the way otherwise.)

publish articles with a date/time set in the future

---

_layouts/essential.html

In working with some HTML PCP mockups in Mockweb, I noticed that `<title>` would sometimes bring in (escaped) HTML tags. I changed it there, so I ported the fix here too.
This fix prevents the title on browser tabs from showing the HTML tags like this:
`Cockpit <strong>test</strong>` — now it would display `Cockpit test`

strip HTML from title strings

---

running.md

For RHEL ≥ 7.5, parts of Cockpit are in Base, but we still want to
recommend Extras to get cockpit-packagekit, and be able to install
cockpit-machines.
On RHEL 8, AppStream is enabled by default, and not having it is not
supported. So clarify that this first step only applies to 7.
On RHEL 8, the default zone has the Cockpit port opened in firewalld.
But point out that with custom zones it needs to be opened.
Fixes #242
----
Rendered preview: https://martinpitt.github.io/cockpit-project.github.io/running.html#rhel

running: Update install instructions for RHEL

---

running.md

Debian 8 (Jessie) has been EOL for a while, and its backports repository
moved to the Archive.

running: Drop obsolete Debian 8 instructions

---

_posts/2019-05-29-cockpit-195.md

The direct link to the package name and version doesn't seem to be
working anymore, so link directly to the build ID.

Update F30 link in Cockpit 195 release notes

---

README.md

I realized bundler isn't always set up to work with a user account. This README update handles it by adding a configuration step.

Add docs to make bundle work as a user

---

_posts/2019-07-10-cockpit-198.md

Apparently the package version links have stopped working.

Cockpit 198: Fix bodhi URL

---

.gitignore
README.md
_scripts/toolbox-create
_scripts/toolbox-delete
_scripts/toolbox-run
_scripts/toolbox-update

- Added scripts to run the website locally in a toolbox container
- Made git ignore the local .gem directory (where I told toolbox to store its gems)
- Updated README with nodejs fix, as CoffeeScript needs a JavaScript engine, to align with container script deps
Fixes #263

Add toolbox-based container scripts

---

assets/site/guide.sass

I noticed an issue with some elements 'overflowing' their padding property, with no apparent visual result that blocked clicking links. Issue was most apparent in the Features section. Tested this in Chrome and Firefox (both on Windows).
The fix involved removing padding from said element's class. There is no apparent visual changes in the page or in any other pages (classification was under the page so I didn't expect that).
**Before:**
<kbd>
</kbd>
**After:**
<kbd>
</kbd>
Also removed a stray comma.

Removed unnecessary padding blocking click in Guide, class .chapters

---

_data/browsers.yml

This allows Cockpit to rely on Promise.prototype.finally() and get rid
of its last custom polyfill.
See https://github.com/cockpit-project/cockpit/issues/12151

update minimum Chrome version to 63

---

_data/distros.yml
running.md

Show the commands how to install and enable it.
The Community Repository is part of the official repositories, so tone
down the text to stop making it sound exceptional/unsupported.
Also mark cockpit as "included" for the same reason.
Preview: https://martinpitt.github.io/cockpit-project.github.io/running.html

running: Update Arch installation instructions

---

running.md

`pacman -Sy <package>` is an unsupported operation that should be
avoided [1] as it can cause a partial upgrade of the system. Instead,
just document how to install only the cockpit package, and separately
document the (uncommon) case when repository indexes don't exist.
Thanks to NEXCydran for pointing this out!
[1] https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported
Fixes commit 36605790126
Fixes #313

running: Avoid partial upgrade in Arch installation instructions

---

assets/site.sass
assets/site/guide.sass

- Add a little more edge padding for narrow screens (small width desktop and mobile
- Deconstruct variable list for mobile, stacking the list when too narrow for side-by-side
- Fix the documentation warnings to match the warnings used on the site

Style fixes  (2020-06-30)

---

running.md

It seems that podman does not pull images on `container runlabel` command.
Fixes https://github.com/cockpit-project/cockpit/issues/14481

Document that cockpit/ws image needs to be pulled

---

assets/site/guide.sass

Fixes documentation warning layout issue in https://cockpit-project.org/guide/latest/embedding.html#embedding-deep and adds spacing between a warning and a paragraph for https://cockpit-project.org/guide/latest/cert-authentication.html#certauth-server-cockpitconf

Warning fixups: Layout and spacing

---

external/bots/README.md
external/source/HACKING.md
external/source/test/README.md

Updated to the latest external docs with the following command:
```sh
toolbox run -c cockpit-website sh -c _scripts/update-external-docs.rb
```
(Which should work on every system when there's a cockpit-website container, made with `_scripts/toolbox-create`.)

Update external docs (2020-11-24)

---

running.md

podman on Fedora CoreOS has stopped looking into the docker.io registry
by default, so that a bare "cockpit/ws" would just check
registry.fedoraproject.org.
This was fixed half a year ago in cockpit [1], but forgotten to be moved
to the website.
[1] https://github.com/cockpit-project/cockpit/commit/2256ae091ee731f
Fixes #360

running: Fix install instructions for Fedora CoreOS

---

_scripts/toolbox-create

As we're controlling the version of Fedora in the toolbox, this makes sure anyone creating a new toolbox container is using Fedora 33, regardless of the version of Fedora used on their host. (Toolbox defaults to the same version as the host when creating new toolbox containers.)
As Fedora 33 has been stable for some time now, this is fine.

scripts: Bump up toolbox-create to F33

---

.github/workflows/update-externals.yml

Run update-external-docs.rb every Thursday, or on manual request.
Fixes #151
-----
I tested this on my fork:
- Until this morning, docs were up to date. My [first run](https://github.com/martinpitt/cockpit-project.github.io/actions/runs/429838721) saw no changes and did not create a pull request, see [this log line](https://github.com/martinpitt/cockpit-project.github.io/runs/1575041303?check_suite_focus=true#step:5:463)
- I [made a fix to our Workflow wiki page](https://github.com/cockpit-project/cockpit/wiki/Workflow/_compare/920ed9cc6de0b4f438dfbb2c85a103182ba592b5)
- Then I [ran this workflow](https://github.com/martinpitt/cockpit-project.github.io/actions/runs/429838721) again, and it created https://github.com/martinpitt/cockpit-project.github.io/pull/3

workflows: Weekly update of external pages

---

_includes/github.html

Fixes #235
Includes support for both repo and wiki links. The link is to the edit mode on GitHub.
Our externals script has included "source:" with URLs in the frontmatter this whole time, with anticipation of this support. :wink:

include: Handle source override in GitHub edit

---

assets/site.sass

I was going to address #231 but looked at the running page instead. I noticed it did have horizontal overflow due to the breakpoint being a little off. I've fixed it, even though it's unrelated to the original issue (which I think was fixed in another commit, a long while ago).

running: Adjust breakpoint for OS table

---

assets/site/guide.sass

Super simple fix: I missed a comma on the title class. Whoops!

guide: Fix typo in CSS (missing comma)

---

_includes/feed.html

Some feed readers support referencing images relative to the `<link>` as `<base href>`,  others do not.
By changing our path referenced images to be absolute instead, _all_ feed readers will be supported (provided they stick to https to avoid mixed content, but that's on their side, not ours).

include/feed: Use absolute URL for images

---

_includes/post.html
_includes/posts.html

Fixed summary mode to only use headlines; spotted in #393. Also added category with a link (when available).

Posts  headline summary and category

---

assets/site.sass

This makes `<abbr>` show up in all browsers with squiggles. Previously, WebKit had issues and didn't style it whatsoever.

style: Improve abbr display across browsers

---

_data/browser_support.yml
_data/browsers.yml
_scripts/update-browser-data.rb

- Switch caniuse DB URL to 'main'
- Add replaceAll check (even though it isn't in caniuse db)
- Manually bump up minimum browser versions
- Update browser support data from script

browser: Update browser checks for replaceAll

---

running/safari.md

Add missing instruction to enable the Develop menu in the settings dialog.
Just saw this and noticed an small instruction missing. Super happy this works now!

running: clarify macOS Safari workaround

---

running.md

Same update as the cockpit/ws container documentation update:
https://github.com/cockpit-project/cockpit/commit/7a289865e7a
----
Preview: https://martinpitt.github.io/cockpit-project.github.io/running.html#coreos

running: Document how to enable password SSH logins on CoreOS

---

_scripts/generate-release-notes.rb

Uploading first draft. There's more work to be done, but it's already working enough for demo purposes.
GOAL:
Have a script that iterates through our repos, finds the release-notes tag, extract the text, and make a draft version of our release notes, ready to edit.
TODO:
- first use of "release notes", "---", and/or something like that... probably with multiple, with a fallback of just using the body notes
- Comments at the top of the files now suggest running through the toolbox-ruby script, simplifying the process, in #432
Pending PR with generated files: https://github.com/cockpit-project/cockpit-project.github.io/pull/431
Preview: https://garrett.github.io/cockpit-project.github.io/blog/cockpit-248.html

script: Generate release notes based on GitHub PRs and tags

---

running.md

The Fedora packages app has been deprecated for a while for now,
see https://discussion.fedoraproject.org/t/https-apps-fedoraproject-org-packages-is-down-and-has-been-for-a-while/23662/3?u=rugk
The suggested alternative is https://src.fedoraproject.org.
Unfortunately, I also found no way to link to the cockpit packages as before. There is only the usual page and also no way to show dependencies:
https://src.fedoraproject.org/rpms/cockpit
As such I just removed the link.

Remove broken link to legacy Fedora packages services

---

external/bots/README.md

Not sure why our docs script didn't run to catch the updates, so I ran this manually.
```
_scripts/toolbox-ruby _scripts/update-external-docs.rb
```
If you'd rather have the bot run the docs script, feel free to close this PR when that happens. :wink:

Update docs (2021-07-06)

---

_data/applications.yml

45drives/cockpit-samba-manager is deprecated - use 45drives/cockpit-file-sharing instead. Also added cockpit-navigator, a useful file manager/browser; and cockpit-benchmark, a storage benchmark utility.  
[File Sharing](https://github.com/45Drives/cockpit-file-sharing)  
[Navigator](https://github.com/45Drives/cockpit-navigator)  
[Benchmark](https://github.com/45Drives/cockpit-benchmark)

Change samba-manager to file-sharing, and add navigator file browser

---

_scripts/generate-release-notes.rb

I moved the title string into the frontmatter, always basing it on Cockpit's own version, allowing for Cockpit itself to have no release-note tags and yet still generate proper release notes.
(Subprojects may have release-note tags still, even if Cockpit itself does not have anything noteworthy.)
Previous version would erroneously grab the first version of something with release notes, which works fine if Cockpit itself has release notes. Whoops.

script: Handle lack of release notes on main repo

---

_scripts/generate-release-notes.rb

Before I forget, here's a possible fix for handling project names with lowercasing, to make @allisonkarlitskaya happier.
I haven't tested it yet, as it's late today and I just want to be done with Release-Notes for now, but I also don't want to forget this.

script: Fix release note repo assumptions & formatting

---

running.md

Debian 10 already has cockpit in the release (although at version 188).
So update the instructions for both 10 and 11 to clarify the backports
situation and recommendation.
Fixes #444

running: Update for Debian 11

---

_scripts/toolbox-create

Fedora 35 beta's toolbox cannot currently run Fedora 34 containers. However, Fedora 34 and Fedora 35 both can run Fedora 35 containers and this script works perfectly well in Fedora 35, so I'm bumping the version.

script: Bump toolbox-create script to Fedora 35

---

_scripts/generate-release-notes.rb

1. I renamed the "released" option but didn't change it in options. Whoops. Fixed and tested locally.
2. Terms lost the newline along the way, breaking definitions. Now fixed.

script: Fix definitions & "released" incrementing

---

_scripts/generate-release-notes.rb

I wrote the script to assume there would always be a body, but the GitHub API returns a nil and Ruby seems to like to change an empty string into a nil sometimes when match and gsub are used.

scripts: Handle empty body in release-notes PRs

---

running.md

This PR adds a few lines to indicate that on Linux Mint, the `UBUNTU_CODENAME` variable is required rather than the `VERSION_CODENAME`.  Linux Mint defines its own version codename separate from Ubuntu's, so the backport command as-is fails.  Other Ubuntu-based distributions may do the same, but Linux Mint is probably the most important to note since it's one of the top five distributions.

Mention adjusted install command needed for Linux Mint

---

_data/applications.yml

Set the new repository for it, and update the package name with what
used in Red Hat distributions.

applications: update the subscription manager plugin

---

_data/applications.yml

Please note: The *maintained* Samba and NFS app is still here.

applications: Delist the old, unmaintained SMB app

---

_posts/2022-05-12-cockpit-269.md

Replace the bodhi search URLs with the links to the actual releases.
The search URLs are only meant to be used as a fallback in case we
forget.

269: Link to specific releases

---

_scripts/update-external-docs.rb

Adding two wiki pages to our externals, so they're on the website and indexed for easy searching.
- https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-NGINX
- https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-Apache-with-LetsEncrypt
Fixes #525

externals: Add proxy wiki pages

---

_scripts/container-run

Without naming and replacing the container, a new container would be
made on each container run, causing a "leak" with lots of containers.
This change keeps your Podman container list tidy.

scripts: Name and replace the container on use

---

_posts/2014-11-13-cockpit-plugin-tutorial.md

Fixes #555
I also updated https://github.com/cockpit-project/cockpit/wiki/Cockpit-Coding-Guidelines to not refer to cockpit.css any more, that will be auto-synced in the next days.
I did not update the screenshots, as they are still current. Apparently we already did the last one when cockpit.css was gone already.
Preview: https://martinpitt.github.io/cockpit-project.github.io/blog/creating-plugins-for-the-cockpit-user-interface.html

plugin tutorial: Adjust for removal of cockpit.css

---

_data/browser_support.yml
_scripts/update-browser-data.rb

Browsers are starting to support the next level of :is/:where.
Unfortunately, it seems our query string only targeted level 1.
Website counterpart to https://github.com/cockpit-project/cockpit/issues/17724 & https://github.com/cockpit-project/cockpit/pull/17726

browser: Update :is() and :where() support test with values

---

_posts/2022-10-20-login-issues.md

See https://launchpad.net/bugs/1990623 -- I pulled some old strings, and it's released now. :tada: 
Rendered view: https://martinpitt.github.io/cockpit-project.github.io/blog/login-issues.html

Login issues: Official fix for Ubuntu 22.04 LTS is now available

---

running.md

Use the same "and later" as for RHEL, to clarify that Cockpit is not only in version 7.
---
see https://github.com/cockpit-project/cockpit/issues/17891#issuecomment-1307816312

running: Clarify CentOS versions

---

running.md

As far as I understood, the Docker Hub image was not updated in quite a long time and was superseded by the quay.io image. Making sure nobody installs out of date software with this update of the documentation.

Updating out of date info about cockpit/ws

---

_scripts/generate-release-notes.rb

generate-release-notes script had Cockpit client link in "footer_dynamic", which was added to footer in loop for each released repo. This caused that footer would contain multiple of the same "Cockpit client" links.
[Cockpit 279 release notes](https://cockpit-project.org/blog/cockpit-279.html) are example of this:

Don't repeat Cockpit client link in blog post

---

running.md

When referring to cockpit package being available through a distro's default package manager for installation, use the 'available' word and not 'included'.
Included is slightly misleading making users think that the package is installed by default in the relevant distro.
Closes #596

Start using 'available' instead of 'included' when referring to cockpit

---

external/source/HACKING.md
external/wiki/Contributing.md
faq.md
index.md
privacy.md

The Cockpit Project is now on Matrix at #cockpit:fedoraproject.org.
Preview: https://allisonkarlitskaya.github.io/cockpit-project.github.io/

various: replace mentions of IRC with Matrix

---

_data/applications.yml

This adds two additional applications for headscale management and cloudflare tunnels overview. Both are in a very early state, but are usable. This also fixes the accidental override of the `sensors` id, which was therefore not shown. 🤦 copy-n-paste mistake.

Add headscale and cloudflared applications

---

_scripts/generate-release-notes.rb

GitHub changed the way they handle images; their URLs might not have an extension now. For the time being, we should assume the images without extensions are PNG files.
We will probably want to download whatever they are and run some identification on them in the future (like the `file` command).
I also switched the string extension and string concat to use native Ruby File.* commands.

scripts: Handle redirects in image URLs

---

assets/lib/search.coffee

While `return scoreA < scoreB` works in Gecko and WebKit and _used to_ work in Blink, sorting "broke" (it still worked, but not as intended) in Chrome at some point.
Switching the less-than comparison to a minus makes all browser engines work the same (as Gecko, WebKit, and an older Blink engine does in either variant).
Preview is at https://garrett.github.io/cockpit-project.github.io/search.html#javascript

search: Fix unstable sorting in Chrome

---

_data/distros.yml
running.md

We test on Arch, so we should mention that on our running/install page.
I've added the tested flag and reordered the distros to keep all tested ones next to each other.

running, data: Promote Arch to "tested"

---

documentation.md

Quick fix for pointing the RHEL8 docs to the new locations

documentation: Fix links to RHEL8 docs

---

assets/site.scss

This adds a little space above a fragment-linked item (foo.html#bar), for in-page linking.
I've added a --scroll-margin variable which can be used to customize it per page. But we rely on the fallback for now.

style: Add a default scroll margin

---

faq.md

https://github.com/cockpit-project/cockpit/issues/8477#issuecomment-1824633520 discovered a missing dependency that completes the solution in the FAQ.
Confirmed on my Raspberry Pi 4b with Ubuntu 22.04.3 LTS (jammy), so I'm improving the FAQ.

fix: add Raspberry Pi required step

---

_posts/2018-04-11-making-a-cockpit-application.md

At some point, cockpit changed the application id and this page linked from documentation includes an outdated example. If used, this results in AppStream metainfo for the app being dropped as it doesn't extend any other app.

Update cockpit metainfo

---

_scripts/generate-release-notes.rb

We already stopped releasing to Fedora 38 so drop that.

Fedora 40 is now released

---

_includes/apps.html

There is a whitespace character trailing the app's title in the https://cockpit-project.org/applications.html page. This appears to be due to the `app-title` text containing additional newline and whitespace characters:
I think this change should resolve the issue, though I am unable to test it due to #725.
I'm opening this PR in case the maintainers agree with the fix without requiring me to resolve the testing issue.

apps: Display title without trailing whitespace

---

_data/applications.yml

It's unmaintained and archived.
Fixes #739

applications: Drop cockpit-certificates

---

running.md

openSUSE Leap 15.6 has cockpit in it https://news.opensuse.org/2024/04/29/try-cockpit-in-leap-rc/

Add openSUSE Leap into the list

---

running.md

I happened to notice several problems with the SUSE section on the "running" page and made a commit to fix these:
1. The last SUSE command was lacking the ``` ending, so it was formatted incorrectly
2. All commands used `#`, which is a comment (in addition to the standard root prompt), so copy/pasting the full line wouldn't work
3. All instructions on the page are done via the root account already, so sudo isn't needed
4. `$EDITOR` actually is set by default and uses the default editor... the "of choice" is implied, as someone can change the editor to whatever they want; this makes it clear to use whatever editor _and_ allows a copy/paste to work

running: Fix SUSE commands

---

_posts/2021-07-05-pcp-grafana.md

Fedora 41+ will only have valkey, and cockpit got adjusted accordingly in https://github.com/cockpit-project/cockpit/pull/20513

2021-07-05-pcp-grafana.md: Update for valkey

---

_scripts/generate-release-notes.rb

Fedora-39 is no longer supported, Fedora-41 was released and we still release to Fedora-40.

scripts: update Fedora releases

---

_data/applications.yml

This is no longer maintained and not available at least RHEL 8 or higher.

applications: drop cockpit-ovirt-dashboard

---

index.md

Jekyll isn't smart enough to escape or translate this so leaving double quote strings generates invalid html.

Replace double quotes from title attribute with a single quote

---

_config.yml

The plugins are currently broken due to a deprecation with Jekyll. This
enables all the plugins again and also takes care of some complaints
that exist for the config itself.
Signed-off-by: Freya Gustavsson <freya@venefilyn.se>

config: Fix Jekyll configuration errors

---

assets/site/guide.scss

We had components that got colors from components or something else than
our own code. This changes table, variablelist and others to inherit the
color from what we set higher up. Should fix dark mode issues
Fixes: #810
Signed-off-by: Freya Gustavsson <freya@venefilyn.se>

css: Inherit color for variablelist

---

_posts/2025-06-25-cockpit-341.md

We usually only show Cockpit's version number.

Fix title to only mention Cockpit
