Makefile
README.md

We want to set `LANG=C` when generating files.
A README helps getting started with adding content.

Update makefile and add README

---

ideals.html

This came up a few times, and last night I just remembered it again. So here it is :-)

ideals: Add "Cockpit is tested"

---

_data/navigation.yml
assets/site.sass
index.md

reworked nav; included on front page

---

_layouts/guide.html
assets/site.sass

This adds the foundation (`layout: guide`) for #87 to work.

add "guide" layout (and CSS) for the static guide

---

_layouts/guide.html
assets/site.sass

includes tree indentation fix; closes #92

fixed guide styling

---

_includes/search_json.html
_includes/search_json_items.html

improved static HTML searching with better blurbs & titles

---

_posts/2017-09-21-cockpit-151.md

Preview: https://martinpitt.github.io/cockpit-project.github.io/blog/cockpit-151.html

Cockpit 151

---

assets/site.sass

fixes definition lists to be more recognizable

improved definition list style

---

_posts/2014-12-16-protocol-interaction.md
external/wiki/Contributing.md

* Fix tutorial for protocol
* Fix tutorial links

Fix tutorials links and content

---

running.md

browser versions: added Edged, removed Android

---

_includes/page_footer.html

added github link to the bottom of the footer

---

assets/site.sass
running.md

running: highlight selected OS

---

_includes/nav.html
_includes/search.html
_layouts/guide.html
assets/lib/blog.sass
assets/lib/search.sass
assets/site.sass
running.md

Commit 06e54f5 fixes issue #51.
The rest of the commits were a result of doing accessibility audits (in Chrome) across the site.

accessibility improvements for contrast, alt text, search, blog, etc.

---

_includes/nav.html
_includes/pagination.html
_includes/search.html
assets/lib/search.coffee
index.md

Added several different accessibility-related fixes as pointed out by the WAVE and Tota11y add-ons for Firefox.

Accessibility fixes

---

_includes/page_footer.html
_layouts/default.html
_layouts/guide.html
index.md

Added several ARIA landmarks around the site to make keyboard navigation and screen reading better.

ARIA landmarks

---

_posts/2018-03-07-cockpit-163.md

/!\ DRAFT, not released yet.
Rendered preview: https://martinpitt.github.io/cockpit-project.github.io/blog/cockpit-163.html

Cockpit 163

---

_scripts/update-external-docs.rb
external/source/HACKING.md
external/source/test/README.md
external/wiki/Contributing.md

I used the script `_scripts/update-external-docs.rb` to update all external docs.
This isn't automated (yet), but could be.

updated external documentation (as of 2018-03-19)

---

assets/lib/minima-unset.sass

See https://github.com/cockpit-project/cockpit-project.github.io/issues/152#issuecomment-374197597

style: fixed a few more minima table stylings

---

_posts/2018-03-28-puppeteer-tests.md
files/starter-kit/check-puppeteer.js

Preview: https://martinpitt.github.io/cockpit-project.github.io/blog/cockpit-custom-test-framework.html

tutorial: Using Cockpit test VMs with your own test framework

---

_posts/2018-04-18-cockpit-166.md

Rendered preview: https://martinpitt.github.io/cockpit-project.github.io/blog/cockpit-166.html

Cockpit 166

---

_posts/2018-05-16-cockpit-168.md

Rendered: https://martinpitt.github.io/cockpit-project.github.io/blog/cockpit-168.html

Cockpit 168

---

_posts/2018-05-28-sso-oauth.md

Rendered: https://mvollmer.github.io/cockpit-project.github.io/blog/sso-oauth.html

blog: SSO and OAuth

---

_posts/2018-05-28-sso-oauth.md

I rewrote the SSO/OAuth blog post to make it flow a little better. :wink:

rewrote oath/sso blog

---

running.md

add click-your-distro instructions

---

_posts/2018-08-08-cockpit-175.md

https://mvollmer.github.io/cockpit-project.github.io/blog/cockpit-175.html

Cockpit 175

---

ideals.md

Fixes #197 
Preview: https://martinpitt.github.io/cockpit-project.github.io/ideals.html

ideals: Fix wrong link to home page

---

_posts/2018-09-05-cockpit-177.md

Rendered preview: https://martinpitt.github.io/cockpit-project.github.io/blog/cockpit-177.html

Cockpit 177

---

_data/navigation.yml

nav: changed "Try it out" to "Install"

---

_posts/2018-09-19-cockpit-178.md

Rendered: https://mvollmer.github.io/cockpit-project.github.io/blog/cockpit-178.html

Cockpit 178

---

assets/site/guide.sass

fixes https://github.com/cockpit-project/cockpit/issues/10204

guide: fix list overlap

---

external/wiki/Contributing.md

external: update contributing doc to fix 404

---

_includes/page_footer.html
assets/site.sass

1. Update year, mainly to show that Cockpit's been around for a while and is current
2. Add "Red Hat sponsored project"
3. Add link to Code of Conduct
4. Made footer responsive in a fancy way using `display: flex`

footer: update year, add CoC & RH sponsored proj.

---

_data/browsers.yml

Updated minimum browser support requirements to require CSS grid.

browser support: grid

---

external/source/HACKING.md
external/source/test/README.md
external/wiki/Contributing.md

Commit includes results from running `_scripts/update-external-docs.rb`

Update docs (2019-07-09); includes bind mount info

---

external/source/HACKING.md
external/source/test/README.md

Commit includes results from running `_scripts/update-external-docs.rb`

Update docs (2019-08-14)

---

index.md

Assumption: Cockpit will always be the first release in a title.

index: Make badge take "and" into consideration

---

external/source/HACKING.md
external/source/test/README.md

Update to the latest versions of HACKING and README

Update external docs (2020-01-23)

---

_posts/2020-01-22-cockpit-211.md

https://mvollmer.github.io/cockpit-project.github.io/blog/cockpit-211.html

Cockpit 211

---

external/source/test/README.md

Pull in changes from test/README

Update external docs (2020-02-20)

---

_posts/2020-03-04-cockpit-214.md

Rendered: https://martinpitt.github.io/cockpit-project.github.io/blog/cockpit-214.html

Cockpit 214

---

_posts/2014-11-13-cockpit-plugin-tutorial.md

Collects post-merge follow-ups from PR #316 
Preview: https://martinpitt.github.io/cockpit-project.github.io/blog/creating-plugins-for-the-cockpit-user-interface.html

Refinements: Creating Plugins for the Cockpit User Interface

---

_posts/2020-05-06-cockpit-ansible.md

Preview: https://martinpitt.github.io/cockpit-project.github.io/blog/cockpit-ansible.html

Add post: Scale up Cockpit troubleshooting to your computing fleet

---

external/source/HACKING.md
external/source/test/README.md

Update docs (2020-05-19)

---

_posts/2020-05-29-cockpit-common-criteria.md

Preview: https://marusak.dev/cockpit-project.github.io/blog/cockpit-common-criteria.html
@larskarlitski @martinpitt WDYT?
There were some other tweaks we did for CC, but I found then awkward to write about. Of course there is a ton of things that are for CC that Cockpit already had, it was just supposed to be what is new.

Article about Cockpit Common Criteria

---

_posts/2020-06-10-cockpit-221.md

https://mvollmer.github.io/cockpit-project.github.io/blog/cockpit-221.html

Cockpit 221

---

_scripts/update-external-docs.rb
external/bots/README.md
external/source/HACKING.md
external/source/test/README.md
external/wiki/Cockpit-Coding-Guidelines.md
external/wiki/Workflow.md

1. Add support for the bots README file in our docs updater script.
2. Sync all external docs to the website, including the bots README.

External docs update  (2020-06-30)

---

_posts/2020-07-08-cockpit-223.md

Page preview: https://kkoukiou.github.io/cockpit-project.github.io/blog/cockpit-223.html

Cockpit 223

---

_scripts/toolbox-create

Minor fixes brought over from Springboard (where I noticed some issues from backporting Cockpit yesterday).

Script fixes

---

assets/site.sass
assets/site/guide.sass
running.md

Update instructions for Debian Buster

---

_posts/2020-08-19-cockpit-226-cockpit-podman-22.md
_posts/2020-10-14-cockpit-230.md

https://gundersanne.github.io/cockpit-project.github.io/blog/cockpit-230#cockpit%20230

Cockpit 230

---

_posts/2020-11-25-cockpit-233.md

Preview: https://allisonkarlitskaya.github.io/cockpit-project.github.io/blog/cockpit-233.html

Cockpit 233

---

external/wiki/Workflow.md

Sync'd up with the most recent docs.
This just changed a bit of the `Workflow.md`.

Update external docs (2020-12-09)

---

_includes/post.html

include, blog: Handle empty authors

---

_includes/search.html

search: Use DuckDuckGo when JS is not enabled

---

_posts/2021-01-21-cockpit-236.md

Preview: https://martinpitt.github.io/cockpit-project.github.io/blog/cockpit-236.html

Cockpit 236

---

_posts/2021-04-05-fmf-unified-testing.md

Preview: https://martinpitt.github.io/cockpit-project.github.io/blog/fmf-unified-testing.html
I'd appreciate some reviews whether this is a coherent and comprehensive story, and of course also fixes to my broken English. Thank you!
@thrix, @TomasTomecek, @psss FYI

post: Unified upstream and downstream testing with TMT and Packit

---

_posts/2021-04-14-cockpit-242.md

Preview: https://marusak.dev/cockpit-project.github.io/blog/cockpit-242.html

Cockpit 242

---

assets/lib/screenshot-gallery.js

When I removed touch support in #398, I accidentally removed scroll wheel support too. Adding it back.

screenshots: Add back scroll wheel support

---

_data/applications.yml
_includes/apps.html
applications.md
assets/site.sass
assets/site/applications.sass
index.md
running.md

Includes links to the page as well.
Fixes #348.

apps: Add application data & page

---

_posts/2021-05-06-pixel-tests.md

Preview: https://mvollmer.github.io/cockpit-project.github.io/blog/pixel-testing.html

Pixel testing blog

---

running.md

As per comment/suggestion in https://github.com/cockpit-project/cockpit-project.github.io/pull/433#issuecomment-874798817
Follow-up of #433 
Thanks @garrett

Link to Cockpit application overview

---

_scripts/generate-release-notes.rb

Options include:
- Preview
- Released, to not increment when Cockpit has been released
- Verbose mode (for debugging)

script/release: Options and error handling

---

_data/authors.yml
_includes/post.html

Better late than never at removing Google+ support. :rofl: 
Also, I've updated my author info since I'm doing blog posts now. :wink:

Remove G+ support; update my author info

---

_posts/2022-02-03-pixel-tests-update.md

https://mvollmer.github.io/cockpit-project.github.io/blog/pixel-testing-update.html

blog: Pixel testing update

---

_data/applications.yml

Also set zfs to be "release" instead of "prerelease".

applications: Change link for ZFS to 45 Drives

---

_posts/2022-02-16-cockpit-263.md

Preview: https://garrett.github.io/cockpit-project.github.io/blog/cockpit-263.html

Cockpit 263

---

_scripts/generate-release-notes.rb

Fix bodhi url fedora version in generation script

---

_scripts/generate-release-notes.rb

Toolbx exposed the $USER. This isn't available to a standard container.
Podman overlay mounts are shown in /etc/mtab however.
User can be inferred from overlay.

scripts: Extract current user from overlay mount

---

documentation.md

Proposing minor changes for RHEL 9. You might want to edit further.

update documentation.md for RHEL 9

---

running.md

running: Copy Debian backport upgrade to Ubuntu

---

_posts/2022-10-20-login-issues.md

Please review ASAP. We need this merged and live on the site quickly.

posts: Login issues blog post

---

_posts/2022-10-20-login-issues.md

As @martinpitt pointed out in https://github.com/cockpit-project/cockpit-project.github.io/pull/569#issuecomment-1285880691

blog: Fix Kinetic spelling

---

_data/distros.yml
running.md

- Remove "supported"
- Clarify "tested" with a note

running: Revised tested table

---

_posts/2022-10-20-login-issues.md

- Removed more distribution-specific instructions
- Added Rocky and Alma to the fixed paragraph
- Reworded sed command
- Added a mention about browser caching

login issues: Updated with current information

---

_posts/2022-11-16-cockpit-280.md

Preview: https://garrett.github.io/cockpit-project.github.io/blog/cockpit-280.html

Cockpit 280

---

assets/site.sass
faq.md

FAQ: Initial version of frequently asked questions

---

documentation.md
faq.md
index.md

Preview:
- FAQ updates on the FAQ: https://garrett.github.io/cockpit-project.github.io/faq.html
Additionally:
- Footer of https://garrett.github.io/cockpit-project.github.io/
- Bottom section of https://garrett.github.io/cockpit-project.github.io/documentation.html

FAQ update

---

external/wiki/Contributing.md

Manual docs update, as we've updated Contribution

docs update (2023-03-02)

---

_scripts/update-external-docs.rb

Added support for rewriting the new relative links in HACKING.md for https://github.com/cockpit-project/cockpit/pull/18509.

scripts: Add two rewrite rules for HACKING

---

documentation.md

I've added a link to Cockpit on SUSE ALP products

Update for SUSE ALP version

---

_data/applications.yml

Add application to manage Tailscale installed on the host.

Add cockpit-tailscale

---

_posts/2023-08-01-tmt-cross-project-testing.md

Preview: https://martinpitt.github.io/cockpit-project.github.io/blog/tmt-cross-project-testing.html

tmt-cross-project-testing: Add failure notifications and current users

---

ideals.md

Use possessive in ideals.md's title

---

running.md

See individual commits for details.
Preview: https://martinpitt.github.io/cockpit-project.github.io/running.html#ubuntu

Update Ubuntu/Mint install instructions

---

_scripts/generate-release-notes.rb

39 has been released and 37 will be EOL soon.

scripts: bump Fedora releases to 39, 38 and drop 37

---

assets/lib/search.scss

Move padding of button into both button and input; allow the form to wrap on mobile.

style: Improve search on mobile

---

_posts/2024-04-24-cockpit-316.md

https://jelly.github.io/cockpit-project.github.io/blog/cockpit-316.html

Cockpit 316

---

_scripts/update-external-docs.rb
external/wiki/Demos-and-Talks.md

Additionally, add the first version of the page to the repo, so it's tracked in git.

Add demos and talks to the docs sync

---

_posts/2024-07-03-cockpit-320.md

Preview: https://martinpitt.github.io/cockpit-project.github.io/blog/cockpit-320.html
This was pre-reviewed with Garrett in the PR.
Still waiting on bodhi.

Cockpit 320

---

documentation.md

no Dolomite anymore but Micro

---

_posts/2024-10-23-cockpit-327.md

Preview: https://martinpitt.github.io/cockpit-project.github.io/blog/cockpit-327.html

Cockpit 327

---

_posts/2024-12-04-cockpit-330.md

Garrett already went over the actual relnotes yesterday directly in the PRs. ~So this just needs bodhi now.~ done
Preview: https://martinpitt.github.io/cockpit-project.github.io/blog/cockpit-330.html

Cockpit 330

---

_posts/2024-06-12-cockpit-318.md
_posts/2024-07-03-cockpit-320.md
_posts/2024-09-25-cockpit-325.md
_posts/2024-10-23-cockpit-327.md
_posts/2024-12-04-cockpit-330.md

All but these articles are posted by "pitti", make them consistent.

Fix my author ID

---

_data/applications.yml

Hello,
We (Clearpath Robotics) have developed a new 3rd party application that we would like to add to the list of available plugins. It is available from source or debian through the instructions in the indicated repo. Please let me know if there is anything else needed.
Thanks,
Hilary

Add ROS 2 Diagnostics 3rd party application
